### PR TITLE
Fix objc_defines

### PR DESCRIPTION
**Pull request by sergeykhliustin**

### CODE REVIEW

**Comment by jwthanh** [comment]
Hi @sergeykhliustin. I am facing the below error due to this pull request on the Xcode 15.3. I reverted it to our fork https://github.com/ahiho/BazelPods for a temporary solution.

```
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
<built-in>:421:2: note: in file included from <built-in>:421:
# 1 "<command line>" 1
 ^
<command line>:28:9: error: 'PB_ENABLE_MALLOC' macro redefined
#define PB_ENABLE_MALLOC 1GDTCOR_VERSION=9.3.0
        ^
<command line>:27:9: note: previous definition is here
#define PB_ENABLE_MALLOC 1
        ^
<built-in>:421:2: note: in file included from <built-in>:421:
# 1 "<command line>" 1
 ^
<command line>:28:9: error: 'PB_ENABLE_MALLOC' macro redefined
#define PB_ENABLE_MALLOC 1GDTCOR_VERSION=9.3.0
        ^
<command line>:27:9: note: previous definition is here
#define PB_ENABLE_MALLOC 1
        ^
<unknown>:0: error: could not build Objective-C module 'SwiftShims'
error: emit-module command failed with exit code 1 (use -v to see invocation)
<built-in>:421:2: note: in file included from <built-in>:421:
# 1 "<command line>" 1
 ^
<command line>:28:9: error: 'PB_ENABLE_MALLOC' macro redefined
#define PB_ENABLE_MALLOC 1GDTCOR_VERSION=9.3.0
        ^
<command line>:27:9: note: previous definition is here
#define PB_ENABLE_MALLOC 1
        ^
<built-in>:421:2: note: in file included from <built-in>:421:
# 1 "<command line>" 1
 ^
<command line>:28:9: error: 'PB_ENABLE_MALLOC' macro redefined
#define PB_ENABLE_MALLOC 1GDTCOR_VERSION=9.3.0
        ^
<command line>:27:9: note: previous definition is here
#define PB_ENABLE_MALLOC 1
        ^
<unknown>:0: error: could not build Objective-C module 'SwiftShims'
error: fatalError
```

**Comment by sergeykhliustin** [comment]
usually, "macro redefined" should be a warning, not an error. do you have any extra compiler flags?

there is an issue in GoogleDataTransport podspec, no space between `PB_ENABLE_MALLOC` and `GDTCOR_VERSION`
https://github.com/CocoaPods/Specs/blob/master/Specs/0/6/a/GoogleDataTransport/9.4.1/GoogleDataTransport.podspec.json#L66

**Comment by jwthanh** [comment]
The issue in GoogleDataTransport is the root cause in my case. It works when I add a space between PB_ENABLE_MALLOC and GDTCOR_VERSION.

@sergeykhliustin Do we have a flag to override it in case?

**Comment by jwthanh** [comment]
@sergeykhliustin Thank you for your update. I tried, and it works now 🎉

**Pull request merged**
